/**
 * CRM MCP Server Permissions
 * Role-based access control and hierarchy-based permissions
 */

import { Employee, Lead, ROLE_HIERARCHY, PermissionCheck, JobRole } from './types'
import { supabase, getSubordinates, isInReportingChain } from './auth'

/**
 * Check if employee can view a lead
 * @param employee - Current employee
 * @param lead - Lead to check
 * @returns Permission check result
 */
export async function canViewLead(
  employee: Employee,
  lead: Lead
): Promise<PermissionCheck> {
  // Owner and directors can view all leads
  if (isTopManagement(employee.job_role)) {
    return { canView: true, canEdit: true, canDelete: true, canAssign: true }
  }

  // Employee can view their own leads
  if (lead.assigned_to === employee.id || lead.generated_by === employee.id) {
    return { canView: true, canEdit: true, canDelete: false, canAssign: false }
  }

  // Managers can view their subordinates' leads
  const subordinates = await getSubordinates(employee.id)
  if (subordinates.includes(lead.assigned_to)) {
    return {
      canView: true,
      canEdit: isManager(employee.job_role),
      canDelete: false,
      canAssign: isManager(employee.job_role),
    }
  }

  // Check if in same team (based on role prefix)
  if (isSameTeam(employee.job_role, lead.assigned_to)) {
    const { data: leadOwner } = await supabase
      .from('crm_employees')
      .select('job_role')
      .eq('id', lead.assigned_to)
      .single()

    if (leadOwner && isHigherRole(employee.job_role, leadOwner.job_role as JobRole)) {
      return { canView: true, canEdit: true, canDelete: false, canAssign: true }
    }
  }

  return {
    canView: false,
    canEdit: false,
    canDelete: false,
    canAssign: false,
    reason: 'Insufficient permissions to access this lead',
  }
}

/**
 * Check if employee can create a lead
 * @param employee - Current employee
 * @returns True if can create
 */
export function canCreateLead(employee: Employee): boolean {
  // All active employees can create leads
  return employee.is_active
}

/**
 * Check if employee can update a lead
 * @param employee - Current employee
 * @param lead - Lead to update
 * @param updates - Fields being updated
 * @returns Permission check result
 */
export async function canUpdateLead(
  employee: Employee,
  lead: Lead,
  updates: Partial<Lead>
): Promise<PermissionCheck> {
  const viewPermission = await canViewLead(employee, lead)

  if (!viewPermission.canView) {
    return viewPermission
  }

  // Check if trying to reassign
  if (updates.assigned_to && updates.assigned_to !== lead.assigned_to) {
    if (!viewPermission.canAssign) {
      return {
        canView: true,
        canEdit: false,
        canDelete: false,
        canAssign: false,
        reason: 'Insufficient permissions to reassign lead',
      }
    }
  }

  return viewPermission
}

/**
 * Check if employee can delete a lead
 * @param employee - Current employee
 * @param lead - Lead to delete
 * @returns Permission check result
 */
export async function canDeleteLead(
  employee: Employee,
  lead: Lead
): Promise<PermissionCheck> {
  // Only top management can delete leads
  if (!isTopManagement(employee.job_role)) {
    return {
      canView: false,
      canEdit: false,
      canDelete: false,
      canAssign: false,
      reason: 'Only owners and directors can delete leads',
    }
  }

  return { canView: true, canEdit: true, canDelete: true, canAssign: true }
}

/**
 * Get accessible lead IDs for employee
 * @param employee - Current employee
 * @returns Array of lead IDs the employee can access
 */
export async function getAccessibleLeadIds(
  employee: Employee
): Promise<string[]> {
  // Top management can access all leads
  if (isTopManagement(employee.job_role)) {
    const { data } = await supabase.from('crm_leads').select('id')
    return data ? data.map((l) => l.id) : []
  }

  // Get subordinates
  const subordinates = await getSubordinates(employee.id)
  const accessibleEmployees = [employee.id, ...subordinates]

  // Get leads assigned to or generated by accessible employees
  const { data } = await supabase
    .from('crm_leads')
    .select('id')
    .or(
      `assigned_to.in.(${accessibleEmployees.join(',')}),generated_by.in.(${accessibleEmployees.join(',')})`
    )

  return data ? data.map((l) => l.id) : []
}

/**
 * Filter leads based on employee permissions
 * @param employee - Current employee
 * @param leads - Array of leads to filter
 * @returns Filtered array of leads
 */
export async function filterLeadsByPermissions(
  employee: Employee,
  leads: Lead[]
): Promise<Lead[]> {
  // Top management can see all leads
  if (isTopManagement(employee.job_role)) {
    return leads
  }

  // Get subordinates
  const subordinates = await getSubordinates(employee.id)
  const accessibleEmployees = [employee.id, ...subordinates]

  // Filter leads
  return leads.filter(
    (lead) =>
      accessibleEmployees.includes(lead.assigned_to) ||
      accessibleEmployees.includes(lead.generated_by)
  )
}

/**
 * Check if role is top management
 * @param role - Job role
 * @returns True if top management
 */
function isTopManagement(role: string): boolean {
  return ['owner', 'ea_to_owner', 'director', 'ea_to_director'].includes(role)
}

/**
 * Check if role is a manager
 * @param role - Job role
 * @returns True if manager
 */
function isManager(role: string): boolean {
  return (
    isTopManagement(role) ||
    role.startsWith('pm_') ||
    role.endsWith('_lead')
  )
}

/**
 * Check if two roles are in the same team
 * @param role1 - First role
 * @param employeeId2 - Second employee ID
 * @returns True if same team
 */
function isSameTeam(role1: string, employeeId2: string): boolean {
  // Extract team prefix (sales, marketing, support)
  const getTeamPrefix = (role: string): string => {
    if (role.startsWith('sales')) return 'sales'
    if (role.startsWith('marketing')) return 'marketing'
    if (role.startsWith('support')) return 'support'
    return 'general'
  }

  // This would need to query the employee's role
  // Simplified version returns true for now
  return true
}

/**
 * Check if role1 has higher hierarchy than role2
 * @param role1 - First role
 * @param role2 - Second role
 * @returns True if role1 is higher
 */
function isHigherRole(role1: string, role2: string): boolean {
  const level1 = ROLE_HIERARCHY[role1 as JobRole] || 0
  const level2 = ROLE_HIERARCHY[role2 as JobRole] || 0
  return level1 > level2
}

/**
 * Check if employee can view analytics
 * @param employee - Current employee
 * @param targetEmployeeId - Optional target employee for filtered analytics
 * @returns Permission check result
 */
export async function canViewAnalytics(
  employee: Employee,
  targetEmployeeId?: string
): Promise<PermissionCheck> {
  // Top management can view all analytics
  if (isTopManagement(employee.job_role)) {
    return { canView: true, canEdit: false, canDelete: false, canAssign: false }
  }

  // Managers can view their team's analytics
  if (isManager(employee.job_role)) {
    if (!targetEmployeeId) {
      return { canView: true, canEdit: false, canDelete: false, canAssign: false }
    }

    const subordinates = await getSubordinates(employee.id)
    if (targetEmployeeId === employee.id || subordinates.includes(targetEmployeeId)) {
      return { canView: true, canEdit: false, canDelete: false, canAssign: false }
    }
  }

  // Regular employees can only view their own analytics
  if (!targetEmployeeId || targetEmployeeId === employee.id) {
    return { canView: true, canEdit: false, canDelete: false, canAssign: false }
  }

  return {
    canView: false,
    canEdit: false,
    canDelete: false,
    canAssign: false,
    reason: 'Insufficient permissions to view analytics for this employee',
  }
}

/**
 * Check if employee can perform bulk operations
 * @param employee - Current employee
 * @returns True if can perform bulk operations
 */
export function canPerformBulkOperations(employee: Employee): boolean {
  // Only managers and above can perform bulk operations
  return isManager(employee.job_role)
}
